language: go
sudo: false
services:
  - docker
script:
  - set -e
  - docker build -t gmemstr/pogo .
  - docker run -d --rm --name test  -p 8000:8000 gmemstre/pogo
  - sleep 10
  - docker ps | grep -q pogo 
  - set +e
matrix:
  include:
    - go: 1.7
    - go: 1.8
    - go: 1.x
    - go: master
  allow_failures:
    - go: master

  before_install:
   - go get github.com/tools/godep

  install:
    - godep restore

  script: 
    - go vet .
    - go test
    - go build
    - ls -al
